### ISSUE TITLE
can't partition table

### ISSUE THREAD

**Issue by gswa** [cavaliercoder/zabbix-pgsql-partitioning#1]
Hello.

I'm pretty sure that I'm doing something wrong, but I don't know what exactly.

I followed steps from readme and stuck with table partitioning.

> zabbix=> SELECT zbx_provision_partitions('history', 'day', 30);
> ERROR:  schema "partitions" does not exist
> CONTEXT:  SQL statement "SELECT (schema_name || '.' || new_table_name)::regclass"
> PL/pgSQL function zbx_provision_partitions(text,text,bigint,text) line 27 at PERFORM

Linux 4.4.0-62-generic #83-Ubuntu SMP x86_64
postgresql/xenial,xenial,now 9.5+173
zabbix-server-pgsql/unknown,now 1:3.2.4-1+xenial amd64

**Comment by gswa** [comment]
Oh looks like 

> CREATE SCHEMA partitions
>   AUTHORIZATION zabbix;

should be preset?

**Comment by cavaliercoder** [comment]
The scripts assume you have manually created and configured a separate Schema for partitions to reside in. This will typically make use of a different Tablespace, etc.

I apologise this is not in the documentation. I'll update the docs to this effect soon.
